name: Create ZIP file and publish release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read version number
      id: get_version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Extract Repositoryname
      id: get_repo
      run: echo "REPO=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV

    - name: Install zip
      run: sudo apt-get install zip

    - name: Create zip-Datei
      run: zip -r $REPO-$VERSION.zip .

    - name: List Files
      run: ls -l

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release-Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./$REPO-$VERSION.zip
        asset_name: $REPO-$VERSION.zip
        asset_content_type: application/zip

