name: Create ZIP file and publish release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read version number
      id: get_version
      run: echo "::set-output name=VERSION::$(cat VERSION)"

    - name: Install zip
      run: sudo apt-get install zip

    - name: Create zip-Datei
      run: zip -r ${{ github.repository }}-${{ steps.get_version.outputs.VERSION }}.zip .

    - name: List Files
      run: ls -l

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release-Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./${{ github.repository }}-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: ${{ github.repository }}-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip

